### ISSUE TITLE
Wrong vehicle image for 6584a802

### ISSUE THREAD

**Issue by gasgaraget** [fredli74/smartcharge-dev#22]
**Correct image address**
* Go to https://tesla.com and sign in
* Right-click the correct image of your vehicle and select "Copy image address"
* Paste the correct image address here
https://static-assets.tesla.com/v1/compositor/?model=mxl&view=STUD_SIDE&size=1440&options=CH04,DRLH,FG02,PI01,COL3-PPSW,RFPX,X021,TP03,WT20&bkba_opt=1&context=design_studio_2

**Comment by fredli74** [comment]
Thank you.
