### ISSUE TITLE
Doesn't poll my car for info

### ISSUE THREAD

**Issue by jramer** [fredli74/smartcharge-dev#499]
**Describe the bug**
Added my refresh token yesterday but the page only stayed in a loading state. Today when I looked the cars name was fetched but the page shows "not polled yet, make sure it is online" and 0%.
Now I'm at a supercharger with the car clearly connected to the internet as the kids are watching Netflix and the car is sending info to the Tesla iPhone app. But I can't find a way to start the polling from smartcharge. 
Tried:
* Reloading page
* Reloading from dropdown
* Disable/enable polling from settings page.

**Expected behavior**
Polling info from Tesla.

**Screenshots**
<img width="1312" alt="Skärmavbild 2021-03-11 kl  16 21 34" src="https://user-images.githubusercontent.com/743717/110810995-97dcf180-8286-11eb-8de4-483fa3acaffb.png">

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.2.2
 - Browser Chrome
 - Version 89.0.4389.82
 Also tried Firefox current ver. and Safari. And iOS Safari latest iOS 14.4?

**Comment by jramer** [comment]
Removed car and re added when also keeping it awake from the iPhone app fixed the problem.

**Comment by fredli74** [comment]
Sorry, was having problems with the Tesla authentication API firewall. I also decided to throw away all old-style access and refresh tokens because they were just timing out. My guess is that you tried to add your vehicle while I was messing around with this update.
