### ISSUE TITLE
Wrong vehicle image for 5bdd8ba4

### ISSUE THREAD

**Issue by mans-larsson** [fredli74/smartcharge-dev#903]
**Correct image address**
* Go to https://tesla.com and sign in
* Right-click the correct image of your vehicle and select "Copy image address"
* Paste the correct image address here
https://static-assets.tesla.com/v1/compositor/?model=ms&view=STUD_SIDE&size=1440&options=$BP01,$ADPX2,$AU01,$DA02,$APH1,$APD1,$X028,$BT85,$P85D,$BS00,$BC0R,$CH01,$CW02,$COSE,$IDCF,$X027,$DRLH,$AF00,$FG02,$X007,$X011,$PI01,$IX01,$X001,$LP01,$X037,$MDLS,$DV4W,$X024,$X003,$PBCW,$PA00,$PS01,$PK00,$X031,$PX00,$PF01,$TM00,$BR05,$REEU,$RFPO,$X013,$ME02,$QREB,$SR01,$SP00,$X019,$SC01,$SU01,$TP02,$TR00,$DSH7,$MT85P,$UTAB,$WTSG,$WXW2,$YF01,$CPF1&bkba_opt=1&crop=1450,600,250,300

**Comment by fredli74** [comment]
Thank you!

Support for Induction20Black wheels added.
06db99c63390c69540cf0197421f4b3c8e9adad5

**Comment by fredli74** [comment]
Oups, sorry, that's the wrong wheels? Are those Super21Gray maybe?

**Comment by mans-larsson** [comment]
Yes, the wheels are wrong, Should be grey 21" turbine wheels. The attached image shows the correct one.

**Comment by fredli74** [comment]
Fixed in bb07eb57b3de930d733eeea28ba9a7cbf831645b
